In [29]:
import pandas as pd
pha_mad_csv = "/media/andivanov/DATA/experiments/VideoMatte5x18/out/pha_mad.csv"

In [30]:
df = pd.read_csv(pha_mad_csv, index_col="clipname")
df

,0,1,2,3,4,5,6,7,8,9,...,690,691,692,693,694,695,696,697,698,699
clipname,,,,,,,,,,,,,,,,,,,,,
0004_construction_site_1,7.164171,6.820726,6.593686,6.645599,6.541586,6.502545,6.504088,6.553767,6.647673,6.600600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0004_0065,5.300724,5.154532,5.139505,5.242321,5.365004,5.333063,5.281310,5.305724,5.355270,5.361413,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0004_classroom_interior_318.br420-1,5.572603,5.406651,5.352770,5.363355,5.558428,5.533588,5.504573,5.494866,5.507898,5.502153,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0004_stairs,7.877445,7.447965,7.262972,7.002901,6.991597,6.956785,7.099918,6.982715,6.975854,6.737404,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0004_0073,7.243823,7.071408,6.345821,6.571187,7.250605,7.535117,7.809495,7.297225,7.230659,6.905245,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0000_0043,6.083330,5.939559,5.676137,5.564572,5.483031,5.419125,5.238784,5.078046,5.036584,4.871058,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0000_church_interior_226.res-church,5.285139,5.096076,4.916774,4.874356,4.792284,4.868983,4.621811,4.622928,4.773162,4.818187,...,5.233997,5.202084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0000_00044,5.296229,5.219982,5.112778,5.031877,5.021851,5.647521,5.224663,4.891616,5.119294,5.007277,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0000_0070,7.618517,5.546540,5.475798,5.259502,5.230434,5.497685,5.937963,6.302206,6.369039,7.073323,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0000_empty_city_115.empty-city-streets-atlanta-georgia-jackson-bridge,5.330616,5.372849,5.209078,5.050626,4.933822,4.957890,4.862919,4.712632,4.887493,4.851724,...,5.235248,5.201366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df['fgr'] = df.index.map(lambda x: x.split("_", 1)[0])
df['bgr'] = df.index.map(lambda x: "".join(x.split("_", 1)[1:]))

In [32]:
metrics_csv = "/media/andivanov/DATA/experiments/VideoMatte5x18/out/metrics.csv"
full_df = pd.read_csv(metrics_csv, index_col="clipname")
df = pd.merge(full_df['bgr_type'], df, left_index=True, right_index=True)
df

,bgr_type,0,1,2,3,4,5,6,7,8,...,692,693,694,695,696,697,698,699,fgr,bgr
clipname,,,,,,,,,,,,,,,,,,,,,
0004_construction_site_1,dynamic,7.164171,6.820726,6.593686,6.645599,6.541586,6.502545,6.504088,6.553767,6.647673,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0004,construction_site_1
0004_0065,semi_dynamic,5.300724,5.154532,5.139505,5.242321,5.365004,5.333063,5.281310,5.305724,5.355270,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0004,0065
0004_classroom_interior_318.br420-1,static,5.572603,5.406651,5.352770,5.363355,5.558428,5.533588,5.504573,5.494866,5.507898,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0004,classroom_interior_318.br420-1
0004_stairs,dynamic,7.877445,7.447965,7.262972,7.002901,6.991597,6.956785,7.099918,6.982715,6.975854,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0004,stairs
0004_0073,semi_dynamic,7.243823,7.071408,6.345821,6.571187,7.250605,7.535117,7.809495,7.297225,7.230659,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0004,0073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0000_0043,semi_dynamic,6.083330,5.939559,5.676137,5.564572,5.483031,5.419125,5.238784,5.078046,5.036584,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0000,0043
0000_church_interior_226.res-church,static,5.285139,5.096076,4.916774,4.874356,4.792284,4.868983,4.621811,4.622928,4.773162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0000,church_interior_226.res-church
0000_00044,dynamic,5.296229,5.219982,5.112778,5.031877,5.021851,5.647521,5.224663,4.891616,5.119294,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0000,00044
0000_0070,semi_dynamic,7.618517,5.546540,5.475798,5.259502,5.230434,5.497685,5.937963,6.302206,6.369039,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0000,0070
0000_empty_city_115.empty-city-streets-atlanta-georgia-jackson-bridge,static,5.330616,5.372849,5.209078,5.050626,4.933822,4.957890,4.862919,4.712632,4.887493,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0000,empty_city_115.empty-city-streets-atlanta-geor...

### Worst frame analysis

In [33]:
df['worst_frame'] = df.max(axis=1, skipna=True, numeric_only=True).values
df['worst_frame'].to_csv("/media/andivanov/DATA/experiments/VideoMatte5x18/out/worst_pha_mad.csv", index_label="clipname")
df['worst_frame']

clipname
0004_construction_site_1                                                 8.643483
0004_0065                                                                6.967237
0004_classroom_interior_318.br420-1                                      7.253078
0004_stairs                                                              7.877445
0004_0073                                                                9.450877
                                                                           ...
0000_0043                                                                7.037420
0000_church_interior_226.res-church                                      9.225325
0000_00044                                                               7.498070
0000_0070                                                                8.405830
0000_empty_city_115.empty-city-streets-atlanta-georgia-jackson-bridge    9.208409
Name: worst_frame, Length: 90, dtype: float64

In [34]:
df.groupby('bgr_type')['worst_frame'].mean()

bgr_type
dynamic         8.688391
semi_dynamic    8.313398
static          7.748497
Name: worst_frame, dtype: float64

In [35]:
df.groupby('bgr')['worst_frame'].mean()

bgr
00037                                                                8.561438
00044                                                                7.256711
0010                                                                 7.748402
0015                                                                 8.402146
0043                                                                 8.900416
0065                                                                 7.118699
0070                                                                 7.496256
0073                                                                10.214467
bar_interior_348.death&co__mg_9751-copy                              8.017515
bikes_2                                                             10.435044
canyon_0369                                                          7.247381
church_interior_226.res-church                                       8.278506
classroom_interior_318.br420-1                                       7.479395
construction_site_1                                                  9.121499
empty_city_115.empty-city-streets-atlanta-georgia-jackson-bridge     7.021053
garage_interior_121.9.-2019-e-3rd-interior-departamento-1            8.447133
stairs                                                               7.778342
yard                                                                 8.977313
Name: worst_frame, dtype: float64

In [36]:
df.groupby('fgr')['worst_frame'].mean()

fgr
0000     8.637725
0001    11.856783
0002     5.611479
0003     6.626979
0004     8.517511
Name: worst_frame, dtype: float64

#### Single video worst frame analysis

In [37]:
df.loc['0001_00037', "worst_frame"]

13.984711647033691

### Intervals of frames analysis

In [38]:
df["mad(0-100)"] = df[list(map(lambda x: str(x), list(range(0, 100))))].mean(axis=1).values
df["mad(100-200)"] = df[list(map(lambda x: str(x), list(range(100, 200))))].mean(axis=1, skipna=True).values
df["mad(200-300)"] = df[list(map(lambda x: str(x), list(range(200, 300))))].mean(axis=1, skipna=True).values
df["mad(300-400)"] = df[list(map(lambda x: str(x), list(range(300, 400))))].mean(axis=1, skipna=True).values
df["mad(400-500)"] = df[list(map(lambda x: str(x), list(range(400, 500))))].mean(axis=1, skipna=True).values
df["mad(500-600)"] = df[list(map(lambda x: str(x), list(range(500, 600))))].mean(axis=1, skipna=True).values
df["mad(600-700)"] = df[list(map(lambda x: str(x), list(range(600, 700))))].mean(axis=1, skipna=True).values

In [39]:
df.groupby('bgr_type')[["mad(0-100)", "mad(100-200)", "mad(200-300)", "mad(300-400)", "mad(400-500)"]].mean()

,mad(0-100),mad(100-200),mad(200-300),mad(300-400),mad(400-500)
bgr_type,,,,,
dynamic,5.951728,6.126154,6.274113,NaN,NaN
semi_dynamic,5.737230,5.937641,6.030815,5.415473,6.111995
static,5.593759,5.672629,5.707582,5.348870,5.698929

In [40]:
df.groupby('bgr')[["mad(0-100)", "mad(100-200)", "mad(200-300)", "mad(300-400)", "mad(400-500)"]].mean()

,mad(0-100),mad(100-200),mad(200-300),mad(300-400),mad(400-500)
bgr,,,,,
00037,6.130317,5.938197,6.205556,NaN,NaN
00044,5.694947,5.786863,NaN,NaN,NaN
0010,5.584221,5.670167,5.804332,NaN,NaN
0015,5.888866,5.880700,6.059046,5.506607,6.111995
0043,6.438392,6.602016,7.114220,NaN,NaN
0065,5.176633,5.480255,5.673498,5.402950,NaN
0070,5.647729,5.623652,5.680475,5.336862,NaN
0073,5.687536,6.369058,5.853318,NaN,NaN
bar_interior_348.death&co__mg_9751-copy,5.779722,5.852008,5.871877,5.515248,6.116893
bikes_2,6.448568,6.751232,NaN,NaN,NaN
canyon_0369,5.348740,5.530787,5.718081,5.181916,5.392085
church_interior_226.res-church,5.691082,5.708603,5.705473,5.356363,5.812142
classroom_interior_318.br420-1,5.408515,5.574090,5.574624,5.334110,5.746759
construction_site_1,5.683474,6.191560,6.358118,NaN,NaN
empty_city_115.empty-city-streets-atlanta-georgia-jackson-bridge,5.370281,5.394967,5.372180,5.301543,5.491681
garage_interior_121.9.-2019-e-3rd-interior-departamento-1,5.964213,5.975319,6.003258,5.404042,5.634013
stairs,5.848855,5.810930,6.258664,NaN,NaN
yard,5.904207,6.278140,NaN,NaN,NaN

In [41]:
df.loc["0001_00037"].filter(like='mad')

mad(0-100)      9.180996
mad(100-200)     7.70695
mad(200-300)    9.569498
mad(300-400)         NaN
mad(400-500)         NaN
mad(500-600)         NaN
mad(600-700)         NaN
Name: 0001_00037, dtype: object

In [42]:
df.loc["0001_00037"][[x for x in range(200, 300)]].values

array([10.26177978515625, 10.39741325378418, 10.694690704345703,
       10.874897003173828, 11.033136367797852, 10.851306915283203,
       9.001768112182617, 8.64156723022461, 8.51428508758545,
       9.402792930603027, 9.224287033081056, 9.723871231079102,
       9.81126308441162, 9.857830047607422, 9.824320793151855,
       9.563823699951172, 9.388510704040527, 9.489785194396973,
       9.687649726867676, 9.914849281311035, 9.965964317321776,
       10.01144313812256, 10.766257286071776, 11.586495399475098,
       12.14793872833252, 13.018467903137209, 13.78791046142578,
       13.57427215576172, 12.342905044555664, 11.830076217651367,
       11.319934844970703, 10.089390754699709, 8.462265014648438,
       7.927443027496338, 7.780984878540039, 8.137994766235352,
       8.136931419372559, 7.994542598724365, 7.91467809677124,
       7.658941745758057, 7.607719898223877, 7.556152820587158,
       7.631044387817383, 7.380919456481934, 7.196776390075684,
       7.101860523223877, 7.528440952301025, 7.410625457763672, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
      dtype=object)

In [43]:
df_dict = {"clip_0": [1, 1, 1], "clip_1": [1, 1]}
df_dummy = pd.DataFrame.from_dict(df_dict, orient="index", columns=[0, 1, 2])
df_dummy

        0  1    2
clip_0  1  1  1.0
clip_1  1  1  NaN

In [44]:
df_dummy.loc["mean"] = df.mean()
df_dummy

          0    1    2
clip_0  1.0  1.0  1.0
clip_1  1.0  1.0  NaN
mean    NaN  NaN  NaN